// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.211
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VuePack
{
				static class Vsix
				{
								public const string Id = "4163aa08-9878-4b1c-a1ee-58ab67f7db5b";
								public const string Name = "Vue.js 2 Pack 2017";
								public const string Description = @"Contains HTML Intellisense and code snippets for the Vue.js JavaScript library";
								public const string Language = "en-US";
								public const string Version = "2.0";
								public const string Author = "vaness11, Mads Kristensen";
								public const string Tags = "vue.js, snippets, javascript";
				}
}
